Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.vars.DYNAMODB_USER_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: notificationId
          AttributeType: N
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: notificationId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1